### ISSUE TITLE
Allow initial to be nullable

### ISSUE THREAD

**Issue by OzairP** [axross/repromised#2]
Allow `initial` prop to be type `Value | null | undefined`. Especially for promises that can return an object, that object may `Required<Value>` so having to define each item is cumbersome.

**Comment by axross** [comment]
This is kind of a restriction in order to infer the arg `value` in `children` as non-nullable value.

To allow the type as nullable (e.g. `string | null`), you can use generic like `<Repromise<string | null>> ...`

**Comment by axross** [comment]
I'm working on #5 to allow `initial` to be optional.

**Comment by axross** [comment]
`initial` is now optional on v0.3.0. Close this issue.
